config/routes.rb
Rails.application.routes.draw do


  #orders controller
  get 'orders', to: 'orders#index', as: 'orders'
  get 'orders/add_to_order_items', as: 'add_to_order_items'
  get 'orders/order_process', to: 'orders#order_process', as: 'order_process'
  get 'orders/increase_item', to: 'orders#increase_item', as: 'increase_item'
  get 'orders/decrease_item', to: 'orders#decrease_item', as: 'decrease_item'
  get 'orders/show/:id', to: 'orders#show', as: 'order_show'
  get 'orders/food_and_set_menu_search', to: 'orders#food_and_set_menu_search', as: 'food_and_set_menu_search'
  get 'orders/destroy_item', to: 'orders#destroy_item', as: 'destroy_item'
  get 'orders/pay_now', to: 'orders#pay_now', as: 'pay_now'
  post 'orders/create_order', to: 'orders#create_order', as: 'create_order'
  post 'orders/create_customer', to: 'orders#create_customer', as: 'create_customer'
  get 'orders/order_print', to: 'orders#order_print', as: 'order_print'
  get 'orders/update_order_status', to: 'orders#update_order_status', as: 'update_order_status'

  # expenses controller
  get 'expenses', to: 'expenses#index', as: 'expenses'
  get 'expense/:id', to: 'expenses#show', as: 'show_expense'
  get 'new', to: 'expenses#new', as: 'new_expense'
  get 'edit/:id', to: 'expenses#edit', as: 'edit_expense'
  patch 'update/:id', to: 'expenses#update', as: 'update_expense'
  delete 'expenses/delete/:id', to: 'expenses#delete', as: 'delete_expense'
  post 'expenses', to: 'expenses#create', as: 'expense'

  # reports_controller

  get 'reports/sales_report', to: 'reports#sales_report', as: 'sales_report'

  #customers controller
  # post 'customers/create', to: 'customers#create', as: 'create_customers'


  resource :orders

  # Devise For active Admin
  devise_for :admin_users, ActiveAdmin::Devise.config

  # Home Controller
  get 'home/index'
  root 'home#index'

  # Devise for employees
  devise_for :employees, controllers: {
      sessions: 'employees/sessions'
  }

  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # devise_for :employees, controllers: {
  #     sessions: 'employees/sessions'
  # }

end

app/views/shared/_flash_message.html.erb
<% flash.each do |name, msg| %>
    <div id ="flash-box">
      <div class="centered flash-message alert alert-dismissable alert-<%= name == :notice or name == 'notice' ? 'success' : 'danger' %>">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        <%= msg.html_safe %>
        <% flash.delete(name) -%>
      </div>
    </div>
<% end %>

app/views/shared/_modal.html.erb
<div class="modal fade modal-wraper" id="modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <!--Header-->
      <div class="modal-header">
        <h4 class="modal-title" id="myModalLabel">Complete order with Payment</h4>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">×</span>
        </button>
      </div>
      <!--Body-->
      <div class="modal-body">

      </div>
      <!--Footer-->
      <div class="modal-footer">
        <button type="button" class="btn btn-close" data-dismiss="modal">Close</button>
        <button class="btn btn-checkout", id="form-submit-btn" >Checkout</button>
      </div>
    </div>
  </div>
</div>

app/views/shared/_modal_content_example.html.erb
<table class="table table-hover">
  <thead>
  <tr>
    <th>#</th>
    <th>Product name</th>
    <th>Price</th>
    <th>Remove</th>
  </tr>
  </thead>
  <tbody>
  <tr>
    <th scope="row">1</th>
    <td>Product 1</td>
    <td>100$</td>
    <td><a><i class="fas fa-times"></i></a></td>
  </tr>
  <tr>
    <th scope="row">2</th>
    <td>Product 2</td>
    <td>100$</td>
    <td><a><i class="fas fa-times"></i></a></td>
  </tr>
  <tr>
    <th scope="row">3</th>
    <td>Product 3</td>
    <td>100$</td>
    <td><a><i class="fas fa-times"></i></a></td>
  </tr>
  <tr>
    <th scope="row">4</th>
    <td>Product 4</td>
    <td>100$</td>
    <td><a><i class="fas fa-times"></i></a></td>
  </tr>
  <tr class="total">
    <th scope="row">5</th>
    <td>Total</td>
    <td>400$</td>
    <td></td>
  </tr>
  </tbody>
</table>

app/views/shared/_modal_footer.html.erb
<div class="modal-footer">
  <button type="button" class="btn btn-outline-primary" data-dismiss="modal">Close</button>
  <button class="btn btn-primary">Checkout</button>
</div>

app/views/shared/_modal_header.html.erb
<div class="modal-header">
  <h4 class="modal-title" id="myModalLabel">Your cart</h4>
  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
    <span aria-hidden="true">×</span>
  </button>
</div>

app/views/shared/_side_nav.html.erb
<div>
  <div class="nav-toggle">
    <i class="fa fa-indent <%= controller.controller_name == "orders"? "":"fa-rotate-180" %> side-nav-icon" aria-hidden="true"></i>
  </div>
</div>

<div style="margin-top: 60px">

  <%= link_to root_path, class: "main-nav-content" do %>
      <div class = "nav-details">
        <i class="fa fa-home" aria-hidden="true"></i><span>Home</span>
      </div>
  <% end %>

  <%= link_to orders_path, class: "main-nav-content" do %>
      <div class = "nav-details">
        <i class="fa fa-shopping-bag" aria-hidden="true"></i><span>Orders</span>
      </div>
  <% end %>

  <%= link_to expenses_path, class: "main-nav-content" do %>
      <div class = "nav-details">
        <i class="fa fa-expand" aria-hidden="true"></i><span>Expense</span>
      </div>
  <% end %>


  <%= link_to sales_report_path, class: "main-nav-content" do %>
      <div class = "nav-details">
        <i class="fa fa-bar-chart" aria-hidden="true"></i><span>Reports</span>
      </div>
  <% end %>

  <%= link_to destroy_employee_session_path, method: :delete, class: "main-nav-content" do %>
      <div class = "nav-details">
        <i class="fa fa-sign-out" aria-hidden="true"></i><span>Logout</span>
      </div>
  <% end %>

</div>

<script type="text/javascript">
    $(document).ready(function(){
        $(".nav-toggle").click(function(){
            $("#nav-content").toggleClass("half-nav");
            $("#main-content").toggleClass("full-content");
        });
        $(".fa-indent").click(function () {
            $(this).toggleClass("fa-rotate-180");
        })
    });
</script>

app/views/shared/_small_side_nav.html.erb
<div class="small-side-nav-wrapper">
  <div class="nav-title"><h5><b>food</b> App</h5></div>
  <% if params[:nav].to_i == 1 %>
      <div class="select-icon" style="margin-top: 4px"></div>
  <% elsif params[:nav].to_i == 2 %>
      <div class="select-icon" style="margin-top: 55px"></div>
  <% elsif params[:nav].to_i == 3 %>
      <div class="select-icon" style="margin-top: 102px"></div>
  <% elsif params[:nav].to_i == 4 %>
      <div class="select-icon" style="margin-top: 155px"></div>
  <% elsif params[:nav].to_i == 5 %>
      <div class="select-icon" style="margin-top: 200px"></div>
  <% end %>

  <div class="nav-content">

    <div>
      <%= link_to orders_path do %>
          <i class="fa fa-cutlery" aria-hidden="true"></i>
      <% end %>
    </div>


    <div>
      <%= link_to root_path(nav: 2) do %>
          <i class="fa fa-glass" aria-hidden="true"></i>
      <% end %>
    </div>

    <div>
      <%= link_to root_path(nav: 3) do %>
          <i class="fa fa-sort-amount-desc" aria-hidden="true"></i>
      <% end %>
    </div>

    <div>
      <%= link_to root_path(nav: 4) do %>
          <i class="fa fa-shopping-bag" aria-hidden="true"></i>
      <% end %>
    </div>

    <div>
      <%= link_to root_path(nav: 5) do %>
          <i class="fa fa-life-ring" aria-hidden="true"></i>
      <% end %>
    </div>
  </div>

</div>

app/views/shared/_top_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Link</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Dropdown
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#">Disabled</a>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>