config/routes.rb
Rails.application.routes.draw do


  #orders controller
  get 'orders', to: 'orders#index', as: 'orders'
  get 'orders/add_to_order_items', as: 'add_to_order_items'
  get 'orders/order_process', to: 'orders#order_process', as: 'order_process'
  get 'orders/increase_item', to: 'orders#increase_item', as: 'increase_item'
  get 'orders/decrease_item', to: 'orders#decrease_item', as: 'decrease_item'
  get 'orders/show/:id', to: 'orders#show', as: 'order_show'
  get 'orders/food_and_set_menu_search', to: 'orders#food_and_set_menu_search', as: 'food_and_set_menu_search'
  get 'orders/destroy_item', to: 'orders#destroy_item', as: 'destroy_item'
  get 'orders/pay_now', to: 'orders#pay_now', as: 'pay_now'
  post 'orders/create_order', to: 'orders#create_order', as: 'create_order'
  post 'orders/create_customer', to: 'orders#create_customer', as: 'create_customer'
  get 'orders/order_print', to: 'orders#order_print', as: 'order_print'
  get 'orders/update_order_status', to: 'orders#update_order_status', as: 'update_order_status'

  # expenses controller
  get 'expenses', to: 'expenses#index', as: 'expenses'
  get 'expense/:id', to: 'expenses#show', as: 'show_expense'
  get 'new', to: 'expenses#new', as: 'new_expense'
  get 'edit/:id', to: 'expenses#edit', as: 'edit_expense'
  patch 'update/:id', to: 'expenses#update', as: 'update_expense'
  delete 'expenses/delete/:id', to: 'expenses#delete', as: 'delete_expense'
  post 'expenses', to: 'expenses#create', as: 'expense'

  # reports_controller

  get 'reports/sales_report', to: 'reports#sales_report', as: 'sales_report'

  #customers controller
  # post 'customers/create', to: 'customers#create', as: 'create_customers'


  resource :orders

  # Devise For active Admin
  devise_for :admin_users, ActiveAdmin::Devise.config

  # Home Controller
  get 'home/index'
  root 'home#index'

  # Devise for employees
  devise_for :employees, controllers: {
      sessions: 'employees/sessions'
  }

  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # devise_for :employees, controllers: {
  #     sessions: 'employees/sessions'
  # }

end

app/models/order.rb
# == Schema Information
#
# Table name: orders
#
#  id             :bigint(8)        not null, primary key
#  customer_name  :string
#  date           :date
#  order_address  :text
#  order_quantity :integer
#  order_status   :string
#  order_table_no :string
#  order_type     :string
#  orderable_type :string
#  paid_amount    :float
#  token_no       :string
#  total_amount   :float
#  total_discount :float
#  total_due      :float
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#  customer_id    :integer
#  employee_id    :integer
#  order_type_id  :integer
#  orderable_id   :integer
#  payment_id     :integer
#

class Order < ApplicationRecord
  validates :order_type, :paid_amount, presence: true

  has_many :order_items
  belongs_to :payment
  belongs_to :employee
  belongs_to :customer, optional: true
  accepts_nested_attributes_for :order_items

  ORDER_TYPE = [
      'Eaten', 'Parcel', 'Home Delivery'
  ]

  ORDER_STATUS = [
      'Pending', 'On the way', 'Complete'
  ]

end

app/models/order_type.rb
# == Schema Information
#
# Table name: order_types
#
#  id              :bigint(8)        not null, primary key
#  order_type_name :string
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class OrderType < ApplicationRecord
  has_many :orders
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  include OrdersHelper

  def index
    @orders = current_employee.orders
  end

  def show
    @order = current_employee.orders.find_by(id: params[:id])
  end

  def update_order_status
    order = current_employee.orders.find_by(id: params[:order_id])
    order.update!(order_status: params[:order_status])
    if params[:index].present?
      redirect_to orders_path
    else
      redirect_to order_show_path(order.id)
    end
  end

  def new
    if session[:cart_id].present?
      @cart = Cart.find_by(id: session[:cart_id])
      unless @cart.present?
        @cart = Cart.create!
        session[:cart_id] = @cart.id
      end
    else
      @cart = Cart.create!
      session[:cart_id] = @cart.id
    end
    @food_menus = FoodMenu.all
    @set_menus = SetMenu.all
  end

  def food_and_set_menu_search
    @cart = Cart.find_by(id: params[:cart_id])
    @food_menus = FoodMenu.where("name LIKE :query", query: "%#{params[:item_name]}%")
    @set_menus = SetMenu.where("name LIKE :query", query: "%#{params[:item_name]}%")
  end

  def edit
    @order = current_employee.orders.find_by(id: params[:id])
    @food_menus = FoodMenu.all
    @set_menus = SetMenu.all
  end

  def order_process
    @order = current_employee.orders.find_by(id: params[:order_id])
  end

  def update
    @order = current_employee.orders.find_by(id: params[:order_id])
    @order.order_status = "Pending"
    @order.total_amount = @order.order_items.sum(:total);
    @order.total_discount = @order.order_items.map{|item| item.discount}.sum
    @order.total_due = @order.total_amount - (params[:order][:paid_amount].to_i + @order.total_discount);
    @order.update(orders_params)
    session[:order_id] = nil
    redirect_to orders_path
  end

  def increase_item
    @cart = Cart.find_by(id: params[:cart_id])
    existing_item = @cart.order_items.find_by(id: params[:food_id]) if params[:food_id].present?
    existing_item.update(total: (existing_item.total+existing_item.orderable.sales_price), qty: existing_item.qty + 1  )
    @items = @cart.order_items
    respond_to do |format|
      format.js {render 'add_to_order_items.js.erb'}
    end
  end

  def decrease_item
    @cart = Cart.find_by(id: params[:cart_id])
    existing_item = @cart.order_items.find_by(id: params[:food_id]) if params[:food_id].present?
    existing_item.update(total: (existing_item.total-existing_item.orderable.sales_price), qty: existing_item.qty - 1  ) if existing_item.qty > 1
    @items = @cart.order_items
    respond_to do |format|
      format.js {render 'add_to_order_items.js.erb'}
    end
  end

  def add_to_order_items
    @cart = Cart.find_by(id: params[:cart_id])
    existing_item = @cart.order_items.find_by(orderable_id: params[:food_menu_id]) if params[:food_menu_id].present?
    existing_item = @cart.order_items.find_by(orderable_id: params[:set_menu_id]) if params[:set_menu_id].present?

    if existing_item.present?
      if params[:food_menu_id].present?
        food_menu = FoodMenu.find_by(id: params[:food_menu_id])
        existing_item.update(qty: existing_item.qty + 1, total: (food_menu.sales_price * (existing_item.qty + 1)))
      elsif params[:set_menu_id].present?
        set_menu = SetMenu.find_by(id: params[:set_menu_id])
        existing_item.update(qty: existing_item.qty + 1, total: (set_menu.sales_price * (existing_item.qty + 1)))
      end
    else
      if params[:food_menu_id].present?
        food_menu = FoodMenu.find_by(id: params[:food_menu_id])
        items = food_menu.order_items.build(cart_id: @cart.id, qty: 1, total: food_menu.sales_price)
        items.discount = food_menu.discount.present?? food_menu.discount.discount_amount : 0
        items.discount_type = food_menu.discount.present?? food_menu.discount.discount_type : ""
        items.save
      elsif params[:set_menu_id].present?
        set_menu = SetMenu.find_by(id: params[:set_menu_id])
        items = set_menu.order_items.build(cart_id: @cart.id, qty: 1, total: set_menu.sales_price  )
        items.discount = set_menu.discount.present?? set_menu.discount.discount_amount : 0
        items.discount_type = set_menu.discount.present?? set_menu.discount.discount_type : ""
        items.save
      end
    end
    @items = @cart.order_items
  end

  def destroy_item
    @cart = Cart.find_by(id: params[:cart_id])
    existing_item = @cart.order_items.find_by(id: params[:food_id]) if params[:food_id].present?
    existing_item.destroy
    @items = @cart.order_items
    respond_to do |format|
      format.js {render 'add_to_order_items.js.erb'}
    end
  end

  def destroy
    order = Order.find(params[:id])
    order.destroy
    redirect_to orders_path
  end

  def pay_now
    @cart = Cart.find_by(id: params[:cart_id])
    @order = current_employee.orders.new
    @payment = Payment.new
    respond_to do |format|
      format.js
    end
  end

  def create_order
    cart = Cart.find(session[:cart_id])
    if cart.order_items.present?
      payment = Payment.new(payment_params)
      payment.employee = current_employee
      payment.total_discount = total_discount(cart.order_items)
      payment.cart_id = session[:cart_id]
      if payment.save
        @order = payment.order
        Cart.destroy(session[:cart_id])
        session[:cart_id] = nil
        flash[:notice] = "Order Complete"

        pdf = render_to_string pdf: "order_receipt", layout: 'pdf', template: "orders/order_summary_pdf.html.erb", encoding: "UTF-8"
        save_path = Rails.root.join('pdfs',"order_receipt_#{@order.id}.pdf")
        File.open(save_path, 'wb') do |file|
          file << pdf
        end
        # system("lpr", "pdfs/order_receipt_#{@order.id}.pdf")

      else
        flash[:denger] = "Something Error"
      end
    else
      flash[:denger] = "Select minimum one items"
    end
    redirect_to new_orders_path
  end

  def create_customer
    Customer.create!(name: params[:name], email: params[:email], phone_no: params[:phone_no], address: params[:address])
  end


  def order_print
    @order = current_employee.orders.find_by(id: params[:id])
    respond_to do |format|
      format.print {render 'orders/order_summary.html.erb', layout: 'print.html.erb'}
    end
  end

  private
  def orders_params
    params.require(:order).permit!
  end

  def payment_params
    params.require(:payment).permit(:last_four_digit, :bank_name, :transaction_no, :pay_type).merge(order_type: params[:order][:order_type], paid_amount: params[:order][:paid_amount], customer_id: params[:order][:customer_id], order_address: params[:order][:order_address], order_table_no: params[:order][:order_table_no]  )
  end

end

app/helpers/orders_helper.rb
module OrdersHelper
  def food_discount(food_id)
    food = FoodMenu.find_by(id: food_id)
    product_discount = "0%"
    if food.discount.present?
      discount = food.discount
      case discount.discount_type
        when Discount::DISCOUNT_TYPE[0]
          product_discount = "#{discount.discount_amount} taka"
        when Discount::DISCOUNT_TYPE[1]
          product_discount = "#{discount.discount_amount} %"
      end
    end
    product_discount
  end

  def set_discount(set_id)
    food = SetMenu.find_by(id: set_id)
    product_discount = "0%"
    if food.discount.present?
      discount = food.discount
      case discount.discount_type
        when Discount::DISCOUNT_TYPE[0]
          product_discount = "#{discount.discount_amount} taka"

        when Discount::DISCOUNT_TYPE[1]
          product_discount = "#{discount.discount_amount} %"
      end
    end
    product_discount
  end

  def total_discount(items)
    total_discount_amount = 0;

    items.each do |item|
      total_discount_amount = total_discount_amount + item_discount_amount(item)
    end
    total_discount_amount
  end

  def item_discount_amount(item)
    item_discount = 0
    if item.discount.present? && item.discount_type == Discount::DISCOUNT_TYPE[0]
      item_discount = item_discount + item.discount * item.qty
    end
    if item.discount.present? && item.discount_type == Discount::DISCOUNT_TYPE[1]
      item_discount = item_discount + (item.discount * item.total)/100
    end
    item_discount
  end

  def order_type(order)
    destination = ""
    if order.present?
      case order.order_type
        when Order::ORDER_TYPE[0]
          destination = "Table No:"
        when Order::ORDER_TYPE[1]
          destination = "Parcel Address:"
        when Order::ORDER_TYPE[2]
          destination = "Home Address:"
      end
    end
    destination
  end

end

app/views/orders/_customer_form.html.erb
<div class="dropdown-menu form-login stop-propagation" role="menu">
  <div class="form-group">
    <label for="exampleInputEmail1">
      <i class="glyphicon glyphicon-envelope"></i> Name
    </label>
    <%= text_field_tag :name, nil, class:"form-control", placeholder: 'Enter customer name'  %>
  </div>
  <div class="form-group">
    <label for="exampleInputEmail1">
      <i class="glyphicon glyphicon-envelope"></i> Email
    </label>
    <%= text_field_tag :email, nil, class:"form-control", placeholder: 'Enter customer email'  %>
  </div>
  <div class="form-group">
    <label for="exampleInputEmail1">
      <i class="glyphicon glyphicon-envelope"></i> Phone No
    </label>
    <%= text_field_tag :phone_no, nil, class:"form-control", placeholder: 'Enter phone number'  %>
  </div>
  <div class="form-group">
    <label for="exampleInputPassword1">
      <i class="glyphicon glyphicon-lock"></i> Address
    </label>
    <%= text_area_tag :address, nil, class:"form-control", placeholder: 'Enter customer address'  %>
  </div>
  <a href="#" class="btn btn-block customer-create-btn" id="customer-form-btn">
    <i class="glyphicon glyphicon-ok"></i> Create
  </a>
</div>


<script type="text/javascript" charset="utf-8">
    $(function () {
        $("#customer-form-btn").click(function () {
            var name = $("#name").val();
            var email = $("#email").val();
            var address = $("#address").val();
            var phone_no = $("#phone_no").val();
            $.ajax({
                type: 'post',
                dataType: 'script',
                data: {name:name, email:email, address:address, phone_no: phone_no},
                url: 'create_customer'
            });
        })
    })
</script>

app/views/orders/_mobile_pay.html.erb
<%= text_field_tag 'payment[last_four_digit]', nil, placeholder: 'Last four Digit of Mobile', class: 'form-control mobile-pay-mobile-number' %>
<%= text_field_tag 'payment[transaction_no]', nil, placeholder: 'Transaction No', class: 'form-control form-field' %>

app/views/orders/_new_foods_pertial.html.erb
<div id = 'new-order', class="col-md-12 new-food-menu-wraper">
  <div class="row">
    <div class="col-md-5 food-head">
      <div class="food-table">
        <table class = "table table-borderless">
          <thead>
          <tr>
            <th>#</th>
            <th>Item Name</th>
            <th>Qty</th>
            <th>Price</th>
            <th>Discount</th>
            <th>Action</th>
          </tr>
          </thead>
          <tbody class="item">
          <%= render 'orders/ordered_items', items: @cart.order_items %>
          </tbody>
        </table>
      </div>
      <div>
        <div class="calculated-amount">
          <span class="calculated-result-show">Sub total: </span> <span class="items-sub-total-amount"><%= (@cart.order_items.collect{ |item| item.total}.sum) %> TK</span><br/>
          <span class="calculated-result-show">Total Discount: </span> <span class="items-total-discount">- <%= total_discount(@cart.order_items) %> TK</span><br/>
          <hr>
          <span class="calculated-result-show">Total: </span> <span class="items-total-amount"><%= (@cart.order_items.collect{ |item| item.total}.sum) - (@cart.order_items.collect{ |item| item.discount}.sum)%> TK</span>
        </div>
      </div>
      <br />
      <%= link_to 'Pay', pay_now_path(cart_id: @cart.id), class: "btn payment", id: "pay-now", remote: true %>
    </div>
    <div class="col-md-7">
      <%= render 'orders/food_and_set_menu', food_menus: @food_menus, set_menus:@set_menus %>
    </div>
  </div>
</div>
<%= render 'shared/modal' %>

<script type="text/javascript" charset="utf-8">

    $( document ).ready(function() {
        $("#form-submit-btn").click(function () {
            $("#new_order").submit();
        });
    });

</script>

app/views/orders/_ordered_items.html.erb
<div class="ordered-items">
  <% items.each.with_index do |item, index| %>
      <tr>
        <td><%= index+1 %></td>
        <td><%= item.orderable.name %></td>
        <td><%= item.qty %></td>
        <td><%= item.orderable.sales_price * item.qty %></td>
        <td><%= item_discount_amount(item) %></td>
        <td class="increase-item">
          <%= link_to increase_item_path(cart_id: @cart.id, food_id:item.id), remote: true do %>
              <i class="fa fa-arrow-up increase-item-icon", aria-hidden="true"></i>
          <% end %>
          <%= link_to decrease_item_path(cart_id: @cart.id, food_id:item.id), remote: true do %>
              <i class="fa fa-arrow-down decrease-item-icon", aria-hidden="true"></i>
          <% end %>
          <%= link_to destroy_item_path(cart_id: @cart.id, food_id:item.id), remote: true do %>
              <i class="fa fa-times destroy-item-icon", aria-hidden="true"></i>
          <% end %>
        </td>
      </tr>
  <% end %>
</div>

app/views/orders/_payment_form.html.erb
<div class="payment-form">
  <%= form_for @order, url: create_order_path do |f| %>
      <div class="form-left-space">
        <%= f.select :order_type, Order::ORDER_TYPE, {prompt: 'Select Order Type'}, { class: 'form-control form-field' }%>
        <div class="row select-customer" id="select-customer">
          <%= render 'select_customer' %>
        </div>
        <div id="order-type-form"></div>
        <%= f.text_field :paid_amount, placeholder: 'Paid Amount', class: 'form-control form-field' %>
        <%= f.text_field :total_amount, value:@cart.order_items.sum(:total)-total_discount(@cart.order_items), disabled:true, placeholder: 'Total Amount', class: 'form-control form-field' %>
        <%#= f.text_field :total_discount, placeholder: 'Total Discount', class: 'form-control form-field' %>
        <%#= f.text_field :total_due, placeholder: 'Total Due', class: 'form-control form-field' %>
      </div>

      <div class="row payment-type-selection">
        <ul class="nav bg-light nav-pills rounded nav-fill mb-4" role="tablist">
          <li class="nav-item">
            <a class="nav-link active" data-toggle="pill" href="#nav-tab-bank" id="cash-pay">
              <i class="fa  fa-university"></i> Cash</a>
          </li>

          <li class="nav-item">
            <a class="nav-link" data-toggle="pill" href="#nav-tab-card" id="card-pay">
              <i class="fa fa-credit-card-alt"></i> Card</a>
          </li>

          <li class="nav-item">
            <a class="nav-link" data-toggle="pill" href="#nav-tab-paypal" id="mobile-pay">
              <i class="fa fa-university"></i> Mobile Banking</a>
          </li>
        </ul>
      </div>
      <div class="pay-form">
        <div id="pay-form">

        </div>
        <%= hidden_field_tag 'payment[pay_type]', 'cash_pay', id: 'payment_type' %>
        <%= hidden_field_tag 'cart_id', @cart.id %>
      </div>
  <% end %>
</div>

<script type="text/javascript" charset="utf-8">

    $("#order_order_type").change(function () {
        var order_type = $(this).val()
        if(order_type == 'Eaten'){
            $("#order-type-form").html("<%= escape_javascript(render 'eaten_form').html_safe %>");
        }
        if( order_type == 'Parcel'){
            $("#order-type-form").html("<%= escape_javascript(render 'parcel_form').html_safe %>");
        }
        if( order_type == 'Home Delivery'){
            $("#order-type-form").html("<%= escape_javascript(render 'home_delivery').html_safe %>");
        }
    });

    $("#cash-pay").click(function () {
        $("#payment_type").val('cash_pay');
        $("#pay-form").html("<%= escape_javascript(render 'cash_pay').html_safe %>");
    });
    $("#card-pay").click(function () {
        $("#payment_type").val('card_pay');
        $("#pay-form").html("<%= escape_javascript(render 'card_pay').html_safe %>");
    });
    $("#mobile-pay").click(function () {
        $("#payment_type").val('mobile_pay');
        $("#pay-form").html("<%= escape_javascript(render 'mobile_pay').html_safe %>");
    });

    $('.stop-propagation').on('click', function (e) {
        e.stopPropagation();
    });

</script>

app/views/orders/_set_items.html.erb
<% set_menus.each do |food| %>
    <%= link_to add_to_order_items_path(set_menu_id: food.id, cart_id: @cart.id), class: 'col-md-3 menu-details', remote: true do%>
        <div class="food-details">
          <%= image_tag("#{food.image}", size: "100x60" ) %>
          <div class="food-name-discount" >
            <%= food.name %> (৳ <%= food.sales_price %>, <%= set_discount(food.id) %>)
          </div>
        </div>
    <% end %>
<% end %>

app/views/orders/add_to_order_items.js.erb
$(".item").html("<%= escape_javascript(render 'ordered_items', items: @items).html_safe %>");
$(".items-sub-total-amount").html("<%= (@items.collect{ |item| item.total}.sum) %> TK");
$(".items-total-discount").html("- <%= total_discount(@items) %> TK");
$(".items-total-amount").html("<%= (@items.collect{ |item| item.total}.sum) - total_discount(@items)%> TK");

app/views/orders/create_customer.js.erb
$("#select-customer").html("<%= escape_javascript(render 'select_customer').html_safe %>");

app/views/orders/edit.html.erb
<div class="col-md-12 new-food-menu-wraper">
  <div class="row">
    <div class="col-md-5 food-head">
      <div style="height: 500px; overflow: auto; background-color: white">
        <table class = "table table-borderless">
          <thead>
          <tr>
            <th>#</th>
            <th>Item Name</th>
            <th>Qty</th>
            <th>Price</th>
            <th>Discount</th>
            <th>Increse</th>
            <th>Dicrese</th>
          </tr>
          </thead>

          <tbody class="item">
          <%= render 'orders/ordered_items', items: @order.order_items %>
          </tbody>

        </table>
      </div>
      <div>
        <div style="text-align: center; margin-top: 14px">
          <span style="float: left">Sub total: </span> <span style="float: right" class="items-sub-total-amount">0.0</span><br/>
          <span style="float: left">Total: </span> <span style="float: right" class="items-total-amount">0.0</span>
        </div>
      </div>
      <br />
      <div id="pay-now" class="btn" style="background-color: fuchsia; width: 100%; color: white" >Pay</div>
      <div id="pay-input"></div>
    </div>
    <div class="col-md-7">
      <%= render 'orders/food_and_set_menu', food_menus: @food_menus, set_menus:@set_menus %>
    </div>
  </div>
</div>

<script type="text/javascript" charset="utf-8">
    $("#pay-now").click(function () {
        $("#pay-input").html("<%= escape_javascript(render 'orders/payment_form').html_safe %>");

    })
</script>

app/views/orders/food_and_set_menu_search.js.erb
$("#food_menus").html("<%= escape_javascript(render 'food_items', food_menus: @food_menus).html_safe %>");
$("#set_menus").html("<%= escape_javascript(render 'set_items', set_menus: @set_menus).html_safe %>");

app/views/orders/new.html.erb
<%= render 'new_foods_pertial' if @food_menus.present? %>
<%= render 'not_found_any_foods' unless @food_menus.present? %>

app/views/orders/order_summary.html.erb
<div class="panel panel-default order-summary-wraper">
  <div class="panel-heading text-align-center">
    <div class="row">
      <div class="col-md-12">
        <h4>Syftet Food Limited</h4>
        <p>Mirpur Branch</p>
        <p>Mirpur dohs, avinue-3, road no-7</p>
        <p>phone, 0172000000, email: info@syfood.com</p>
      </div>
    </div>
  </div>
  <div class="panel-body">
    <div>Payment Type: <%= @order.payment.pay_type.humanize if @order.payment.present?%></div>
    <table class="table">
      <tbody>
      <tr>
        <td>
          <div class="float-left">Item/Description</div>
          <div class="float-right">Amount</div>
        </td>
      </tr>
      <tr class="table-top-bottom-border">
        <td>
          <% @order.order_items.each_with_index do |item, index| %>
              <div>
                <div class="float-left"><%= item.orderable.name %>:</div>
                <div class="float-right">
                  <%= item.qty %> x <%= item.orderable.sales_price.round(2) - item_discount_amount(item)%> = <%= item.qty*(item.orderable.sales_price.round(2) - item_discount_amount(item)) %>TK
                </div>
              </div><br />
          <% end %>
        </td>
      </tr>
      <tr class="table-top-bottom-border">
        <td>
          <div>
            <div class="float-left">Total:</div>
            <div class="float-right">
              <%= @order.order_items.sum(:total) - total_discount(@order.order_items)%> TK
            </div>
          </div>
        </td>
      </tr>
      </tbody>
    </table>

    <div class="text-align-center">
      <p>**Powred by: Syftet Limited, Mirpur, Dhaka**</p>
      <p>**Contact No : +88 017299991000**</p>
    </div>

  </div>
</div>

app/views/orders/show.html.erb
<div class = "order-show-wrap">
  <h4>Order Details
    <%= link_to order_print_path(id: @order.id, format: 'print'), target: '_blank', class: 'btn order-print-button print-order-details' do %>
        <i class="fa fa-print"></i> Print
    <% end %>
  </h4>
  <table class="table">
    <thead class="black white-text">
    <tr>
      <th scope="col">Order Type: </th>
      <th scope="col"><%= order_type(@order) %></th>
      <th scope="col">Order Status: </th>
      <th scope="col">Total Amount: </th>
      <th scope="col">Total Discount: </th>
      <th scope="col">Payable Amount: </th>
      <th scope="col">Paid Amount: </th>
      <th scope="col">Total Due: </th>
      <th scope="col">Pay Type: </th>
      <th scope="col">Customer Name: </th>
    </tr>
    </thead>
    <tbody>
    <tr>
      <td><%= @order.order_type %></td>
      <td><%= @order.order_address %><%= @order.order_table_no %></td>

      <td>
        <div class="float-left"> <%= @order.order_status %> </div>
        <div class="dropdown show float-left order_type" style="margin-left: 5px">
          <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"></a>
          <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
            <%= link_to Order::ORDER_STATUS[0], update_order_status_path(order_status: Order::ORDER_STATUS[0], order_id: @order.id), class: "dropdown-item" %>
            <%= link_to Order::ORDER_STATUS[1], update_order_status_path(order_status: Order::ORDER_STATUS[1], order_id: @order.id), class: "dropdown-item" %>
            <%= link_to Order::ORDER_STATUS[2], update_order_status_path(order_status: Order::ORDER_STATUS[2], order_id: @order.id), class: "dropdown-item" %>
          </div>
        </div>
      </td>

      <td><%= @order.order_items.sum(:total)%></td>
      <td><%= total_discount(@order.order_items) %></td>
      <td><%= @order.order_items.sum(:total) - total_discount(@order.order_items) %></td>
      <td><%= @order.paid_amount %></td>
      <td><%= @order.order_items.sum(:total) - total_discount(@order.order_items) - @order.paid_amount %></td>
      <td><%= @order.payment.pay_type.humanize if @order.payment.present?%></td>
      <td><%= @order.customer.name if @order.customer.present? %></td>
    </tr>
    </tbody>
  </table>
  <hr>
  <br />
  <h4>Order Items</h4>
  <table class="table">
    <thead class="black white-text">
    <tr>
      <th scope="col">#</th>
      <th scope="col">Food Name</th>
      <th scope="col">Price</th>
      <th scope="col">Discount</th>
      <th scope="col">Image</th>
    </tr>
    </thead>
    <tbody>
    <% @order.order_items.each_with_index do |item, index| %>
        <tr>
          <td><%= index+1 %></td>
          <td><%= item.orderable.name %></td>
          <td><%= item.orderable.sales_price.round(2) %></td>
          <td><%= item.orderable.discount.present?? item_discount_amount(item):0.0%></td>
          <td><%= image_tag("#{item.orderable.image}", size: '120x80') %></td>
        </tr>
    <% end %>
    </tbody>
  </table>
</div>