config/routes.rb
Rails.application.routes.draw do


  #orders controller
  get 'orders', to: 'orders#index', as: 'orders'
  get 'orders/add_to_order_items', as: 'add_to_order_items'
  get 'orders/order_process', to: 'orders#order_process', as: 'order_process'
  get 'orders/increase_item', to: 'orders#increase_item', as: 'increase_item'
  get 'orders/decrease_item', to: 'orders#decrease_item', as: 'decrease_item'
  get 'orders/show/:id', to: 'orders#show', as: 'order_show'
  get 'orders/food_and_set_menu_search', to: 'orders#food_and_set_menu_search', as: 'food_and_set_menu_search'
  get 'orders/destroy_item', to: 'orders#destroy_item', as: 'destroy_item'
  get 'orders/pay_now', to: 'orders#pay_now', as: 'pay_now'
  post 'orders/create_order', to: 'orders#create_order', as: 'create_order'
  post 'orders/create_customer', to: 'orders#create_customer', as: 'create_customer'
  get 'orders/order_print', to: 'orders#order_print', as: 'order_print'
  get 'orders/update_order_status', to: 'orders#update_order_status', as: 'update_order_status'

  # expenses controller
  get 'expenses', to: 'expenses#index', as: 'expenses'
  get 'expense/:id', to: 'expenses#show', as: 'show_expense'
  get 'new', to: 'expenses#new', as: 'new_expense'
  get 'edit/:id', to: 'expenses#edit', as: 'edit_expense'
  patch 'update/:id', to: 'expenses#update', as: 'update_expense'
  delete 'expenses/delete/:id', to: 'expenses#delete', as: 'delete_expense'
  post 'expenses', to: 'expenses#create', as: 'expense'

  # reports_controller

  get 'reports/sales_report', to: 'reports#sales_report', as: 'sales_report'

  #customers controller
  # post 'customers/create', to: 'customers#create', as: 'create_customers'


  resource :orders

  # Devise For active Admin
  devise_for :admin_users, ActiveAdmin::Devise.config

  # Home Controller
  get 'home/index'
  root 'home#index'

  # Devise for employees
  devise_for :employees, controllers: {
      sessions: 'employees/sessions'
  }

  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # devise_for :employees, controllers: {
  #     sessions: 'employees/sessions'
  # }

end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController

  def index
    @expenses = current_employee.expenses
  end

  def show
    @expense = current_employee.expenses.find(params[:id])
  end

  def new
    @expense = current_employee.expenses.new
  end

  def create
    expense = current_employee.expenses.build(expense_params)
    expense.date = Date.today
    expense.save
    redirect_to expenses_path
  end

  def edit
    @expense = current_employee.expenses.find(params[:id])
  end

  def update
    expense = current_employee.expenses.find(params[:id])
    expense.update(expense_params)
    redirect_to expenses_path
  end

  def delete
    expense = current_employee.expenses.find(params[:id])
    expense.destroy
    redirect_to expenses_path
  end

  private
  def expense_params
    params.require(:expense).permit(:title, :amount, :expense_category_id)
  end

end

app/helpers/expenses_helper.rb
module ExpensesHelper
end

app/views/expenses/_form.html.erb
<%= form_for @expense, url: url do |expense| %>
    <div class="form-group">
      <%= expense.label :title %>
      <%= expense.text_field :title, class: "form-control" %>
      <%= expense.label :amount %>
      <%= expense.text_field :amount, class: "form-control" %>
      <%= expense.label :category%>
      <%= expense.select :expense_category_id, ExpenseCategory.all.collect{|category| [category.name, category.id ]}, {prompt: 'Select Category'}, {class: 'form-control'} %>
      <%= expense.submit class: 'btn expense-button'%>
    </div>
<% end %>

app/views/expenses/edit.html.erb
<div style="margin: 10px 10px 0 10px;">
  <%= render 'form', url: 'update_expense_path' %>
</div>

app/views/expenses/index.html.erb
<div class="expense-head">
  <div class="expense-title"><b>Expense List</b></div>
  <%= link_to 'New Expense', new_expense_path, class: 'btn btn-info new-order-btn new-expense' %>
</div>
<div class="expenses-wrap">
  <table class="table table-striped">
    <thead>
    <tr>
      <th>SL</th>
      <th>Expense info</th>
      <th>Amount</th>
      <th>Date</th>
      <th>Category</th>
      <th>Action</th>
    </tr>
    </thead>
    <tbody>
    <% @expenses.each.with_index do |expense, index| %>
        <tr>
          <td><%= index+1 %></td>
          <td><%= expense.title %></td>
          <td><%= expense.amount %></td>
          <td><%= expense.date %></td>
          <td><%= expense.expense_category.name %></td>
          <td>
            <div class="dropdown show">
              <a class="btn dropdown-toggle expense-action-button" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Action
              </a>

              <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                <%= link_to 'View', show_expense_path(expense.id), class: "dropdown-item" %>
                <%= link_to 'Edit', edit_expense_path(expense.id), class: "dropdown-item"  %>
                <%= link_to 'Delete', delete_expense_path(expense.id), method: :delete, class: "dropdown-item" %>
              </div>
            </div>
          </td>
        </tr>
    <% end %>
    </tbody>
  </table>
</div>

app/views/expenses/new.html.erb
<div style="margin: 10px 10px 0 10px;">
  <%= render 'form', url: 'expense_path' %>
</div>

app/views/expenses/show.html.erb
<div>
  <h4>Expense</h4>
</div>
<div>
  <table class="table table-striped">
    <thead>
    <tr>
      <th>Expense Title:</th>
      <th>Expense Amount:</th>
      <th>Date:</th>
    </tr>
    </thead>
    <tbody>
    <tr>
      <td><%= @expense.title %></td>
      <td><%= @expense.amount %></td>
      <td><%= @expense.date %></td>
    </tr>
    </tbody>
  </table>
</div>