config/routes.rb
Rails.application.routes.draw do


  #orders controller
  get 'orders', to: 'orders#index', as: 'orders'
  get 'orders/add_to_order_items', as: 'add_to_order_items'
  get 'orders/order_process', to: 'orders#order_process', as: 'order_process'
  get 'orders/increase_item', to: 'orders#increase_item', as: 'increase_item'
  get 'orders/decrease_item', to: 'orders#decrease_item', as: 'decrease_item'
  get 'orders/show/:id', to: 'orders#show', as: 'order_show'
  get 'orders/food_and_set_menu_search', to: 'orders#food_and_set_menu_search', as: 'food_and_set_menu_search'
  get 'orders/destroy_item', to: 'orders#destroy_item', as: 'destroy_item'
  get 'orders/pay_now', to: 'orders#pay_now', as: 'pay_now'
  post 'orders/create_order', to: 'orders#create_order', as: 'create_order'
  post 'orders/create_customer', to: 'orders#create_customer', as: 'create_customer'
  get 'orders/order_print', to: 'orders#order_print', as: 'order_print'
  get 'orders/update_order_status', to: 'orders#update_order_status', as: 'update_order_status'

  # expenses controller
  get 'expenses', to: 'expenses#index', as: 'expenses'
  get 'expense/:id', to: 'expenses#show', as: 'show_expense'
  get 'new', to: 'expenses#new', as: 'new_expense'
  get 'edit/:id', to: 'expenses#edit', as: 'edit_expense'
  patch 'update/:id', to: 'expenses#update', as: 'update_expense'
  delete 'expenses/delete/:id', to: 'expenses#delete', as: 'delete_expense'
  post 'expenses', to: 'expenses#create', as: 'expense'

  # reports_controller

  get 'reports/sales_report', to: 'reports#sales_report', as: 'sales_report'

  #customers controller
  # post 'customers/create', to: 'customers#create', as: 'create_customers'


  resource :orders

  # Devise For active Admin
  devise_for :admin_users, ActiveAdmin::Devise.config

  # Home Controller
  get 'home/index'
  root 'home#index'

  # Devise for employees
  devise_for :employees, controllers: {
      sessions: 'employees/sessions'
  }

  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # devise_for :employees, controllers: {
  #     sessions: 'employees/sessions'
  # }

end

app/models/set_menu.rb
# == Schema Information
#
# Table name: set_menus
#
#  id          :bigint(8)        not null, primary key
#  cost_price  :integer
#  image       :string
#  name        :string
#  sales_price :float
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class SetMenu < ApplicationRecord
  has_many :food_menu_set_menus
  has_many :food_menus, through: :food_menu_set_menus, dependent: :destroy
  has_many :order_items, as: :orderable, dependent: :destroy
  has_one :discount, as: :discountable, dependent: :destroy

  accepts_nested_attributes_for :food_menus
  mount_uploader :image, AvatarUploader

  validates :name, :cost_price, :sales_price, presence: true

end

app/views/admin/set_menus/_select_food.html.erb
<div class="food-wraper">
  <%= semantic_form_for [:admin, @set_menu] do |f| %>
      <%= f.semantic_errors *f.object.errors.keys %>
      <%= f.inputs do %>
          <%= f.input :name %>
          <%= f.input :cost_price %>
          <%= f.input :sales_price %>
          <%= f.input :image, :as => :file %>
          <div class="left-space">
            <%FoodMenu.all.each do |food|%>
                <div class="food-menu">
                  <div><%= image_tag("#{food.image}", size: '120x100')%></div>
                  <div><b><%= food.name %></b></div>
                  <%= check_box_tag "set_menu[food_menu_ids][]", food.id %>
                </div>
            <%end%>
          </div>
      <% end %>
      <%= f.actions %>
  <% end %>
</div>